### ISSUE TITLE
Readme example fails

### ISSUE THREAD

**Issue by zhdanjj** [SReject/jassl#1]
I've tried to run an example from readme and it fails
<details>

![image](https://user-images.githubusercontent.com/22837399/64082266-009ff100-cd15-11e9-8361-829d4487c287.png)

</details>

https://runkit.com/embed/rsr7nl7rzn11

But if I fill array with zero it's ok

**Comment by SReject** [comment]
This has been fixed as of commit 939bfac1ad1c591e9c7895ad39855cad866090ba and will appear in 1.0.13 

To be clear this was not a documentation bug. It was an implementation bug.

**Comment by zhdanjj** [comment]
Thanks
